with xyz as (
select xzone,xper,xyear,(select coalesce((select xcode from xmapbag where zid=opchallandt.zid 
and xtypecat=opchallandt.xtypecat and xitem=opchallandt.xitem),'Customer Bag'))  Bag_type,
(select xitemold from caitem where zid=opchallandt.zid and xitem=opchallandt.xitem )item,xqtychl
from opchallandt where xconfirmt between  '2020-01-01 06:00:00.000' and '2020-10-29 06:00:00.000'
and xstatuschl='3-Invoiced' and xdiv<>'Bag Plant')
 select xzone,
 --jan
 sum(case when Bag_type='1 PLY' and item='PCC-BM' and xper='1'  then xqtychl else 0 end)PCC_BM_1_jan,
 sum(case when Bag_type='2 PLY' and item='PCC-BM' and xper='1' then xqtychl else 0 end)PCC_BM_2_jan,
 sum(case when Bag_type='1 PLY' and item='OPC' and xper='1' then xqtychl else 0 end )OPC_1_jan,
 sum(case when Bag_type='2 PLY' and item='OPC' and xper='1' then xqtychl else 0 end )OPC_2_jan,
 sum(case when Bag_type='1 PLY' and item='PPC' and xper='1' then xqtychl else 0 end )PPC_1_jan,
 sum(case when Bag_type='2 PLY' and item='PPC' and xper='1' then xqtychl else 0 end )PPC_2_jan,
 sum(case when Bag_type='1 PLY' and item='PCC-AM' and xper='1' then xqtychl else 0 end )PCC_AM_1_jan,
 sum(case when Bag_type='2 PLY' and item='PCC-AM' and xper='1' then xqtychl else 0 end )PCC_AM_2_jan,
 sum(case when Bag_type='Bulk'  and xper='1' then xqtychl else 0 end )Bulk_jan,
 coalesce(SUM (case when xper='1' then xqtychl end),0) jan_Total,
 --feb
 sum(case when Bag_type='1 PLY' and item='PCC-BM' and xper='2'  then xqtychl else 0 end)PCC_BM_1_feb,
 sum(case when Bag_type='2 PLY' and item='PCC-BM' and xper='2' then xqtychl else 0 end)PCC_BM_2_feb,
 sum(case when Bag_type='1 PLY' and item='OPC' and xper='2' then xqtychl else 0 end )OPC_1_feb,
 sum(case when Bag_type='2 PLY' and item='OPC' and xper='2' then xqtychl else 0 end )OPC_2_feb,
 sum(case when Bag_type='1 PLY' and item='PPC' and xper='2' then xqtychl else 0 end )PPC_1_feb,
 sum(case when Bag_type='2 PLY' and item='PPC' and xper='2' then xqtychl else 0 end )PPC_2_feb,
 sum(case when Bag_type='1 PLY' and item='PCC-AM' and xper='2' then xqtychl else 0 end )PCC_AM_1_feb,
 sum(case when Bag_type='2 PLY' and item='PCC-AM' and xper='2' then xqtychl else 0 end )PCC_AM_2_feb,
 sum(case when Bag_type='Bulk'  and xper='2' then xqtychl else 0 end )Bulk_feb,
 coalesce(SUM (case when xper='2' then xqtychl end),0) Feb_Total,
 --mar
 sum(case when Bag_type='1 PLY' and item='PCC-BM' and xper='3'  then xqtychl else 0 end)PCC_BM_1_mar,
 sum(case when Bag_type='2 PLY' and item='PCC-BM' and xper='3' then xqtychl else 0 end)PCC_BM_2_mar,
 sum(case when Bag_type='1 PLY' and item='OPC' and xper='3' then xqtychl else 0 end )OPC_1_mar,
 sum(case when Bag_type='2 PLY' and item='OPC' and xper='3' then xqtychl else 0 end )OPC_2_mar,
 sum(case when Bag_type='1 PLY' and item='PPC' and xper='3' then xqtychl else 0 end )PPC_1_mar,
 sum(case when Bag_type='2 PLY' and item='PPC' and xper='3' then xqtychl else 0 end )PPC_2_mar,
 sum(case when Bag_type='1 PLY' and item='PCC-AM' and xper='3' then xqtychl else 0 end )PCC_AM_1_mar,
 sum(case when Bag_type='2 PLY' and item='PCC-AM' and xper='3' then xqtychl else 0 end )PCC_AM_2_mar,
 sum(case when Bag_type='Bulk'  and xper='3' then xqtychl else 0 end )march_jan,
  coalesce(SUM (case when xper='3' then xqtychl end),0) March_Total,
 --Apr
 sum(case when Bag_type='1 PLY' and item='PCC-BM' and xper='4'  then xqtychl else 0 end)PCC_BM_1_april,
 sum(case when Bag_type='2 PLY' and item='PCC-BM' and xper='4' then xqtychl else 0 end)PCC_BM_2_april,
 sum(case when Bag_type='1 PLY' and item='OPC' and xper='4' then xqtychl else 0 end )OPC_1_april,
 sum(case when Bag_type='2 PLY' and item='OPC' and xper='4' then xqtychl else 0 end )OPC_2_april,
 sum(case when Bag_type='1 PLY' and item='PPC' and xper='4' then xqtychl else 0 end )PPC_1_april,
 sum(case when Bag_type='2 PLY' and item='PPC' and xper='4' then xqtychl else 0 end )PPC_2_april,
 sum(case when Bag_type='1 PLY' and item='PCC-AM' and xper='4' then xqtychl else 0 end )PCC_AM_1_april,
 sum(case when Bag_type='2 PLY' and item='PCC-AM' and xper='4' then xqtychl else 0 end )PCC_AM_2_april,
 sum(case when Bag_type='Bulk'  and xper='4' then xqtychl else 0 end )April_jan,
  coalesce(SUM (case when xper='4' then xqtychl end),0) April_Total,
 --May
 sum(case when Bag_type='1 PLY' and item='PCC-BM' and xper='5'  then xqtychl else 0 end)PCC_BM_1_may,
 sum(case when Bag_type='2 PLY' and item='PCC-BM' and xper='5' then xqtychl else 0 end)PCC_BM_2_may,
 sum(case when Bag_type='1 PLY' and item='OPC' and xper='5' then xqtychl else 0 end )OPC_1_may,
 sum(case when Bag_type='2 PLY' and item='OPC' and xper='5' then xqtychl else 0 end )OPC_2_may,
 sum(case when Bag_type='1 PLY' and item='PPC' and xper='5' then xqtychl else 0 end )PPC_1_may,
 sum(case when Bag_type='2 PLY' and item='PPC' and xper='5' then xqtychl else 0 end )PPC_2_may,
 sum(case when Bag_type='1 PLY' and item='PCC-AM' and xper='5' then xqtychl else 0 end )PCC_AM_1_may,
 sum(case when Bag_type='2 PLY' and item='PCC-AM' and xper='5' then xqtychl else 0 end )PCC_AM_2_may,
 sum(case when Bag_type='Bulk'  and xper='5' then xqtychl else 0 end )May_jan,
  coalesce(SUM (case when xper='5' then xqtychl end),0) May_Total,
 --jun
 sum(case when Bag_type='1 PLY' and item='PCC-BM' and xper='6'  then xqtychl else 0 end)PCC_BM_1_jun,
 sum(case when Bag_type='2 PLY' and item='PCC-BM' and xper='6' then xqtychl else 0 end)PCC_BM_2_jun,
 sum(case when Bag_type='1 PLY' and item='OPC' and xper='6' then xqtychl else 0 end )OPC_1_jun,
 sum(case when Bag_type='2 PLY' and item='OPC' and xper='6' then xqtychl else 0 end )OPC_2_jun,
 sum(case when Bag_type='1 PLY' and item='PPC' and xper='6' then xqtychl else 0 end )PPC_1_jun,
 sum(case when Bag_type='2 PLY' and item='PPC' and xper='6' then xqtychl else 0 end )PPC_2_jun,
 sum(case when Bag_type='1 PLY' and item='PCC-AM' and xper='6' then xqtychl else 0 end )PCC_AM_1_jun,
 sum(case when Bag_type='2 PLY' and item='PCC-AM' and xper='6' then xqtychl else 0 end )PCC_AM_2_jun,
 sum(case when Bag_type='Bulk'  and xper='6' then xqtychl else 0 end )Jun_jan,
 coalesce(SUM (case when xper='6' then xqtychl end),0) Jun_Total,
 --july
 sum(case when Bag_type='1 PLY' and item='PCC-BM' and xper='7'  then xqtychl else 0 end)PCC_BM_1_july,
 sum(case when Bag_type='2 PLY' and item='PCC-BM' and xper='7' then xqtychl else 0 end)PCC_BM_2_july,
 sum(case when Bag_type='1 PLY' and item='OPC' and xper='7' then xqtychl else 0 end )OPC_1_july,
 sum(case when Bag_type='2 PLY' and item='OPC' and xper='7' then xqtychl else 0 end )OPC_2_july,
 sum(case when Bag_type='1 PLY' and item='PPC' and xper='7' then xqtychl else 0 end )PPC_1_july,
 sum(case when Bag_type='2 PLY' and item='PPC' and xper='7' then xqtychl else 0 end )PPC_2_july,
 sum(case when Bag_type='1 PLY' and item='PCC-AM' and xper='7' then xqtychl else 0 end )PCC_AM_1_july,
 sum(case when Bag_type='2 PLY' and item='PCC-AM' and xper='7' then xqtychl else 0 end )PCC_AM_2_july,
 sum(case when Bag_type='Bulk'  and xper='7' then xqtychl else 0 end )July_jan,
 coalesce(SUM (case when xper='7' then xqtychl end),0) July_Total,
  --aug
 sum(case when Bag_type='1 PLY' and item='PCC-BM' and xper='8'  then xqtychl else 0 end)PCC_BM_1_aug,
 sum(case when Bag_type='2 PLY' and item='PCC-BM' and xper='8' then xqtychl else 0 end)PCC_BM_2_aug,
 sum(case when Bag_type='1 PLY' and item='OPC' and xper='8' then xqtychl else 0 end )OPC_1_aug,
 sum(case when Bag_type='2 PLY' and item='OPC' and xper='8' then xqtychl else 0 end )OPC_2_aug,
 sum(case when Bag_type='1 PLY' and item='PPC' and xper='8' then xqtychl else 0 end )PPC_1_aug,
 sum(case when Bag_type='2 PLY' and item='PPC' and xper='8' then xqtychl else 0 end )PPC_2_aug,
 sum(case when Bag_type='1 PLY' and item='PCC-AM' and xper='8' then xqtychl else 0 end )PCC_AM_1_aug,
 sum(case when Bag_type='2 PLY' and item='PCC-AM' and xper='8' then xqtychl else 0 end )PCC_AM_2_aug,
 sum(case when Bag_type='Bulk'  and xper='8' then xqtychl else 0 end )Aug_jan,
 coalesce(SUM (case when xper='8' then xqtychl end),0) Aug_Total,
   --sep
 sum(case when Bag_type='1 PLY' and item='PCC-BM' and xper='9'  then xqtychl else 0 end)PCC_BM_1_sep,
 sum(case when Bag_type='2 PLY' and item='PCC-BM' and xper='9' then xqtychl else 0 end)PCC_BM_2_sep,
 sum(case when Bag_type='1 PLY' and item='OPC' and xper='9' then xqtychl else 0 end )OPC_1_sep,
 sum(case when Bag_type='2 PLY' and item='OPC' and xper='9' then xqtychl else 0 end )OPC_2_sep,
 sum(case when Bag_type='1 PLY' and item='PPC' and xper='9' then xqtychl else 0 end )PPC_1_sep,
 sum(case when Bag_type='2 PLY' and item='PPC' and xper='9' then xqtychl else 0 end )PPC_2_sep,
 sum(case when Bag_type='1 PLY' and item='PCC-AM' and xper='9' then xqtychl else 0 end )PCC_AM_1_sep,
 sum(case when Bag_type='2 PLY' and item='PCC-AM' and xper='9' then xqtychl else 0 end )PCC_AM_2_sep,
 sum(case when Bag_type='Bulk'  and xper='9' then xqtychl else 0 end )Sept_jan,
 coalesce(SUM (case when xper='9' then xqtychl end),0) Sept_Total,
   --oct
 sum(case when Bag_type='1 PLY' and item='PCC-BM' and xper='10'  then xqtychl else 0 end)PCC_BM_1_oct,
 sum(case when Bag_type='2 PLY' and item='PCC-BM' and xper='10' then xqtychl else 0 end)PCC_BM_2_oct,
 sum(case when Bag_type='1 PLY' and item='OPC' and xper='10' then xqtychl else 0 end )OPC_1_oct,
 sum(case when Bag_type='2 PLY' and item='OPC' and xper='10' then xqtychl else 0 end )OPC_2_oct,
 sum(case when Bag_type='1 PLY' and item='PPC' and xper='10' then xqtychl else 0 end )PPC_1_oct,
 sum(case when Bag_type='2 PLY' and item='PPC' and xper='10' then xqtychl else 0 end )PPC_2_oct,
 sum(case when Bag_type='1 PLY' and item='PCC-AM' and xper='10' then xqtychl else 0 end )PCC_AM_1_oct,
 sum(case when Bag_type='2 PLY' and item='PCC-AM' and xper='10' then xqtychl else 0 end )PCC_AM_2_oct,
 sum(case when Bag_type='Bulk'  and xper='10' then xqtychl else 0 end )Oct_jan,
 coalesce(SUM (case when xper='10' then xqtychl end),0) Oct_Total,
 SUM(xqtychl) Total
from xyz group by xzone